In [26]:
from molmod import *

In [27]:
from __future__ import print_function
import os
os.chdir("/home/akniga/chro/Azidation/In vacuo/M1/TS2/wocu2ts")

In [28]:
mol = io.gamess.PunchFile("PUNCH")

In [38]:
ts = molecules.Molecule(mol.numbers, mol.coordinates, mol.title, mol.masses, graph=None, symbols=mol.symbols, unit_cell=None)



/home/akniga/anaconda3/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
/home/akniga/anaconda3/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(value.dtype, self.npdtype):


In [54]:
mol.molecule.set_default_graph()

AttributeError: 'PunchFile' object has no attribute 'molecule'

In [20]:
import nglview as ng

In [36]:
print(ts.inertia_tensor)


[[2507494.59518861  976330.64314949 1064051.64963244]
 [ 976330.64314949 8932969.88826243   14612.40063786]
 [1064051.64963244   14612.40063786 7092577.99708232]]


In [39]:
ts.set_default_graph()

/home/akniga/anaconda3/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
/home/akniga/anaconda3/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `bool` to `np.generic` is deprecated. In future, it will be treated as `np.bool_ == np.dtype(bool).type`.
  if not np.issubdtype(value.dtype, self.npdtype):
/home/akniga/anaconda3/lib/python3.6/site-packages/molmod/utils.py:228: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if not np.issubdtype(value.dtype, self.npdtype):


In [41]:
print("All edges (or bonds)")
print(ts.graph.edges)

All edges (or bonds)
(frozenset({0, 1}), frozenset({8, 5}), frozenset({11, 5}), frozenset({11, 6}), frozenset({1, 14}), frozenset({11, 14}), frozenset({16, 14}), frozenset({3, 5}), frozenset({4, 6}), frozenset({17, 2}), frozenset({3, 7}), frozenset({4, 7}), frozenset({3, 12}), frozenset({9, 6}), frozenset({20, 22}), frozenset({18, 20}), frozenset({10, 7}), frozenset({4, 13}), frozenset({19, 15}), frozenset({19, 21}))


In [43]:
i, j = ts.graph.edges[2]
print("The indexes of the second bond:", i, "and", j)

The indexes of the second bond: 11 and 5


In [44]:
for i, j in ts.graph.edges:
    if ts.numbers[i] == 6 and ts.numbers[j] == 1:
        print("C-H bond:", i, j)
    elif ts.numbers[j] == 6 and ts.numbers[i] == 1:
        print("C-H bond:", j, i)

C-H bond: 5 8
C-H bond: 3 12
C-H bond: 6 9
C-H bond: 7 10
C-H bond: 4 13


In [47]:
print("All neighbors:")
print(ts.graph.neighbors)


All neighbors:
{0: frozenset({1}), 1: frozenset({0, 14}), 2: frozenset({17}), 3: frozenset({12, 5, 7}), 4: frozenset({13, 6, 7}), 5: frozenset({8, 3, 11}), 6: frozenset({9, 11, 4}), 7: frozenset({10, 3, 4}), 8: frozenset({5}), 9: frozenset({6}), 10: frozenset({7}), 11: frozenset({5, 6, 14}), 12: frozenset({3}), 13: frozenset({4}), 14: frozenset({16, 1, 11}), 15: frozenset({19}), 16: frozenset({14}), 17: frozenset({2}), 18: frozenset({20}), 19: frozenset({21, 15}), 20: frozenset({18, 22}), 21: frozenset({19}), 22: frozenset({20})}


In [48]:
print("Number of atoms:", ts.size)
print("Shape of the distances array:", ts.graph.distances.shape)


Number of atoms: 23
Shape of the distances array: (23, 23)


In [51]:
mask = (ts.graph.distances <= 3) & (ts.graph.distances != 0)
# For a nice print output, the mask is converted to integers.
print("Mask of atom pairs that are typically involved in valence interactions:")
print(mask.astype(int))



Mask of atom pairs that are typically involved in valence interactions:
[[0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 0 0 0 0]
 [0 1 0 1 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 

In [52]:
print("Isomorphisms in the form of one-to-one mappings")
for symmetry in ts.graph.symmetries:
    print(symmetry)

Isomorphisms in the form of one-to-one mappings


ValueError: A pattern_graph must not be a disconnected graph.